### ISSUE TITLE
OLED monitor HDR display splash screen

### ISSUE THREAD

**Issue by JonsonWzz** [NootInc/NootedRed#81]
MI LAPTOP 15.6 OLED
After installing the Hackintosh, hit the NootedRed and find the flash screen constantly, turn off the high dynamic display in the monitor preference to resume normal, but the monitor brightness control does not take effect

**Comment by ChefKissInc** [comment]
@JonsonWzz ?

**Comment by ChefKissInc** [comment]
According to my sources, OLED screens have no brightness controls on macOS even on Intel

**Comment by ChefKissInc** [comment]
We're gonna need a video of what you mean with the flashing when HDR is on

**Comment by ChefKissInc** [comment]
And it looks like HDR does not work on macOS either, the flickering seems to happen on real Macs as well

**Comment by baisong57** [comment]
I also have the problem, My laptop has an OLED screen, and after loading the corresponding kernel and patch, I found that although I can drag the brightness bar when HDR is turned off, the brightness has not actually changed. When HDR is turned on, not only can automatic brightness be used to adjust it, but manual adjustment can also be used, but the problem is that the screen will keep flashing at this time. When I adjust the screen brightness and want to turn off HDR, the screen brightness will not remain unchanged, but will automatically adjust to the maximum value again.
